# Generated by Django 5.0.6 on 2024-07-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
